### ISSUE TITLE
does not recognize more than one whitespaces 

### ISSUE THREAD

**Issue by Kevin-Aaaquil** [srm-kzilla/octavia#24]
# Expected Behavior
The command `#oc  play <song_name/url>` should play the song or add it to queue. Note the diffrence between
`#oc play <song_name>` & `#oc  play <song_name>` is one extra space between the words `#oc` & `play`

# Current Behavior

![image](https://user-images.githubusercontent.com/73784677/128411903-146e822c-03e9-4823-a31c-8c0698730c1d.png)

Although this is not a big deal, this can be removed by changing
```js
 const messageArray = message.content.trim().split(' ');
```
TO
```js
 const messageArray = message.content.trim().split(/[ ]+/);
```

**Comment by ruddha2001** [comment]
@Kevin-Aaaquil would you like to work on this issue?

**Comment by Kevin-Aaaquil** [comment]
Yes, sure, why not

**Comment by ruddha2001** [comment]
@Kevin-Aaaquil the issue has been assigned. Let me know if you face any problems or have any queries.
Please ask for a review from me once a PR is made.
